name: CI

on:
  push:
    branches:
      - main

jobs:
  test-build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn
      - name: test
        env:
          CI: true
          COVERAGE: true
          FLAKEY: false
        run: |
          yarn test
